@extends('erp.layouts.app')

@section('title', 'Libros Contables')

@section('breadcrumb')
    <a href="{{ route('erp.contabilidad.index') }}" class="text-stone-500 hover:text-stone-900 transition-colors">Contabilidad</a>
    <span class="mx-2 text-stone-300">/</span>
    <span class="text-stone-900">Libros Contables</span>
@endsection

@section('content')
<div class="max-w-7xl mx-auto">
    <!-- Header: Industrial Jurisdiction -->
    <div class="mb-16 text-center">
        <div class="flex items-center justify-center gap-4 mb-4">
            <span class="w-12 h-1 bg-primary rounded-full shadow-[0_0_15px_rgba(206,255,94,0.4)]"></span>
            <p class="text-[12px] font-black text-stone-400 uppercase tracking-[0.4em] italic leading-none">Legal & Fiscal Jurisdictions</p>
            <span class="w-12 h-1 bg-primary rounded-full shadow-[0_0_15px_rgba(206,255,94,0.4)]"></span>
        </div>
        <h2 class="text-5xl md:text-6xl font-headline font-black text-stone-950 italic uppercase tracking-tighter leading-none">
            Ledger <span class="text-stone-300 not-italic">Portals</span>
        </h2>
    </div>

    <!-- Portal Bento Grid: Master Compliance -->
    <div class="grid grid-cols-1 md:grid-cols-2 gap-8 pb-16">
        
        <!-- Libro Diario -->
        <a href="{{ route('erp.contabilidad.libro-diario') }}" class="group bg-white border border-stone-100 p-10 rounded-[40px] hover:shadow-2xl hover:shadow-stone-200 transition-all duration-500 relative overflow-hidden">
            <div class="absolute -right-8 -bottom-8 opacity-[0.03] group-hover:opacity-[0.08] transition-opacity rotate-12">
                <span class="material-symbols-outlined text-[180px]">menu_book</span>
            </div>
            <div class="flex flex-col h-full relative z-10">
                <div class="flex items-center gap-6 mb-10">
                    <div class="w-16 h-16 bg-stone-950 text-primary rounded-2xl flex items-center justify-center group-hover:scale-110 transition-transform duration-500 shadow-2xl shadow-stone-950/20">
                        <span class="material-symbols-outlined text-3xl">menu_book</span>
                    </div>
                    <div>
                        <h3 class="text-2xl font-headline font-black text-stone-950 uppercase italic tracking-tighter leading-none mb-2">General Ledger</h3>
                        <p class="text-[11px] font-black text-stone-400 uppercase tracking-[0.2em] italic">AE_JOURNAL_MASTER_FEED</p>
                    </div>
                </div>
                <p class="text-stone-400 text-[12px] font-black uppercase tracking-[0.1em] leading-relaxed italic mb-10">
                    Chronological logic of all accounting operations, asientos, and patrimonial transmissions for the active fiscal cycle.
                </p>
                <div class="mt-auto pt-8 border-t border-stone-50 flex items-center justify-between text-[11px] font-black text-primary uppercase tracking-[0.3em] italic">
                    <span class="group-hover:translate-x-2 transition-transform italic">Initiate Ledger Access</span>
                    <span class="material-symbols-outlined text-xl group-hover:rotate-45 transition-transform">north_east</span>
                </div>
            </div>
        </a>

        <!-- Libro de Ventas -->
        <a href="{{ route('erp.contabilidad.libro-ventas') }}" class="group bg-white border border-stone-100 p-10 rounded-[40px] hover:shadow-2xl hover:shadow-stone-200 transition-all duration-500 relative overflow-hidden">
            <div class="absolute -right-8 -bottom-8 opacity-[0.03] group-hover:opacity-[0.08] transition-opacity rotate-12">
                <span class="material-symbols-outlined text-[180px]">chrome_reader_mode</span>
            </div>
            <div class="flex flex-col h-full relative z-10">
                <div class="flex items-center gap-6 mb-10">
                    <div class="w-16 h-16 bg-primary text-stone-950 rounded-2xl flex items-center justify-center group-hover:scale-110 transition-transform duration-500 shadow-2xl shadow-primary/20">
                        <span class="material-symbols-outlined text-3xl">chrome_reader_mode</span>
                    </div>
                    <div>
                        <h3 class="text-2xl font-headline font-black text-stone-950 uppercase italic tracking-tighter leading-none mb-2">Sales Ledger</h3>
                        <p class="text-[11px] font-black text-stone-400 uppercase tracking-[0.2em] italic">TX_REVENUE_AUDIT_LOG</p>
                    </div>
                </div>
                <p class="text-stone-400 text-[12px] font-black uppercase tracking-[0.1em] leading-relaxed italic mb-10">
                    Precision control of invoicing, credit notations, and fiscal tax debit generated by commercial transactions.
                </p>
                <div class="mt-auto pt-8 border-t border-stone-50 flex items-center justify-between text-[11px] font-black text-stone-950 uppercase tracking-[0.3em] italic">
                    <span class="group-hover:translate-x-2 transition-transform italic">Generate Fiscal Report</span>
                    <span class="material-symbols-outlined text-xl group-hover:rotate-45 transition-transform">north_east</span>
                </div>
            </div>
        </a>

        <!-- Libro de Caja -->
        <a href="{{ route('erp.contabilidad.libro-caja') }}" class="group bg-white border border-stone-100 p-10 rounded-[40px] hover:shadow-2xl hover:shadow-stone-200 transition-all duration-500 relative overflow-hidden">
            <div class="absolute -right-8 -bottom-8 opacity-[0.03] group-hover:opacity-[0.08] transition-opacity rotate-12">
                <span class="material-symbols-outlined text-[180px]">savings</span>
            </div>
            <div class="flex flex-col h-full relative z-10">
                <div class="flex items-center gap-6 mb-10">
                    <div class="w-16 h-16 bg-stone-50 text-stone-300 rounded-2xl flex items-center justify-center group-hover:bg-primary group-hover:text-stone-950 transition-colors duration-500">
                        <span class="material-symbols-outlined text-3xl">savings</span>
                    </div>
                    <div>
                        <h3 class="text-2xl font-headline font-black text-stone-950 uppercase italic tracking-tighter leading-none mb-2">Cash Flow Ledger</h3>
                        <p class="text-[11px] font-black text-stone-400 uppercase tracking-[0.2em] italic">LIQUID_ASSET_MONITOR</p>
                    </div>
                </div>
                <p class="text-stone-400 text-[12px] font-black uppercase tracking-[0.1em] leading-relaxed italic mb-10">
                    High-precision audit of cash influx and outflow. Daily reconciliation of commercial treasury liquidity.
                </p>
                <div class="mt-auto pt-8 border-t border-stone-50 flex items-center justify-between text-[11px] font-black text-stone-400 uppercase tracking-[0.3em] italic group-hover:text-primary transition-colors">
                    <span class="group-hover:translate-x-2 transition-transform italic">Audit Liquid Feed</span>
                    <span class="material-symbols-outlined text-xl group-hover:rotate-45 transition-transform">north_east</span>
                </div>
            </div>
        </a>

        <!-- Libros Legales -->
        <a href="{{ route('erp.contabilidad.libros-legales') }}" class="group bg-stone-950 p-10 rounded-[40px] shadow-2xl relative overflow-hidden">
            <div class="absolute inset-0 opacity-[0.03] group-hover:opacity-[0.06] transition-opacity" style="background-image: radial-gradient(#ceff5e 2px, transparent 2px); background-size: 24px 24px;"></div>
            <div class="absolute -right-8 -bottom-8 opacity-[0.05] group-hover:opacity-[0.15] transition-opacity rotate-12">
                <span class="material-symbols-outlined text-[180px] text-white">gavel</span>
            </div>
            <div class="flex flex-col h-full relative z-10">
                <div class="flex items-center gap-6 mb-10">
                    <div class="w-16 h-16 bg-primary text-stone-950 rounded-2xl flex items-center justify-center group-hover:rotate-12 transition-transform duration-500">
                        <span class="material-symbols-outlined text-3xl">law</span>
                    </div>
                    <div>
                        <h3 class="text-2xl font-headline font-black text-white uppercase italic tracking-tighter leading-none mb-2">Regulatory Codex</h3>
                        <p class="text-[11px] font-black text-stone-500 uppercase tracking-[0.2em] italic">GOV_COMPLIANCE_ENFORCER</p>
                    </div>
                </div>
                <p class="text-stone-400 text-[12px] font-black uppercase tracking-[0.1em] leading-relaxed italic mb-10">
                    Preparation of Purchase, Sales, and Inventory books according to SENIAT regulations and VEN-NIF protocols.
                </p>
                <div class="mt-auto pt-8 border-t border-white/5 flex items-center justify-between text-[11px] font-black text-primary uppercase tracking-[0.3em] italic">
                    <span class="group-hover:translate-x-2 transition-transform italic">Validate Compliance</span>
                    <span class="material-symbols-outlined text-xl group-hover:rotate-45 transition-transform">north_east</span>
                </div>
            </div>
        </a>

    </div>

    <!-- Advisory: Fiduciary Protocol -->
    <div class="bg-stone-950 border border-stone-800 p-10 rounded-[40px] flex flex-col md:flex-row items-center gap-8 relative overflow-hidden group shadow-2xl">
        <div class="absolute inset-0 opacity-[0.02] bg-primary group-hover:opacity-[0.04] transition-opacity"></div>
        <div class="w-16 h-16 bg-stone-900 border border-stone-800 rounded-full flex items-center justify-center text-primary flex-shrink-0 shadow-2xl relative z-10">
            <span class="material-symbols-outlined text-3xl animate-pulse">verified_user</span>
        </div>
        <div class="relative z-10">
            <p class="text-[12px] font-black text-white uppercase tracking-[0.2em] leading-relaxed italic italic">
                System Advisory: All ledger transmissions within this portal adhere to VEN-NIF fiduciary standards and are cryptographically verified for regulatory audit readiness by the Alpha Finance Node.
            </p>
        </div>
    </div>
</div>
@endsection
